apiVersion: v1
kind: Pod
metadata:
  name: dockerdemo.example.com
  labels:
    app: dockerdemo
spec:
  containers:
  - name: dockerdemo
    image: travuru/dockerdemo
    ports:
    - name: app-port
      containerPort: 8080
