apiVersion: v1
kind: ReplicationController
metadata:
  name: dockerdemo-replica-controller
spec:
  replicas: 2
  selector:
    app: dockerdemo
  template:
    metadata:
      labels:
        app: dockerdemo
    spec:
      containers:
      - name: dockerdemo
        image: travuru/dockerdemo
        ports:
        - name: app-port
          containerPort: 8080